global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'n8n-primary'
    static_configs:
      - targets: ['primary.railway.internal:5678']
        labels:
          service: 'n8n'
          instance: 'primary'

  - job_name: 'n8n-worker'
    static_configs:
      - targets: ['worker.railway.internal:5678']
        labels:
          service: 'n8n'
          instance: 'worker'

  - job_name: 'n8n-worker-2'
    static_configs:
      - targets: ['worker-2.railway.internal:5678']
        labels:
          service: 'n8n'
          instance: 'worker-2'

  - job_name: 'n8n-webhook-processor'
    static_configs:
      - targets: ['webhook-processor.railway.internal:5678']
        labels:
          service: 'n8n'
          instance: 'webhook-processor'
