global:
  scrape_interval: 15s # Default scrape interval

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

   - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter.railway.internal:9187']
        labels:
          service: 'postgres'
          project: 'n8n'
    # Monitors your database

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter.railway.internal:9121']
        labels:
          service: 'redis'
          project: 'n8n'
    # Monitors your queue
