global:
  scrape_interval: 15s
  scrape_timeout: 10s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'n8n-primary'
    scheme: https
    metrics_path: '/metrics'
    static_configs:
      - targets: ['n8n.reech.co:443']
        labels:
          service: 'n8n'
          instance: 'primary'
          environment: 'production'
  - job_name: 'n8n-worker'
    scheme: https
    metrics_path: '/metrics'
    static_configs:
      - targets: ['worker-production-48db.up.railway.app:443']
        labels:
          service: 'n8n'
          instance: 'worker'
          environment: 'production'
  - job_name: 'n8n-worker-2'
    scheme: https
    metrics_path: '/metrics'
    static_configs:
      - targets: ['worker-2-production-f42c.up.railway.app:443']
        labels:
          service: 'n8n'
          instance: 'worker-2'
          environment: 'production'
  - job_name: 'n8n-webhook-processor'
    scheme: https
    metrics_path: '/metrics'
    static_configs:
      - targets: ['webhook-processor-production-61a4.up.railway.app:443']
        labels:
          service: 'n8n'
          instance: 'webhook-processor'
          environment: 'production'
  - job_name: 'postgres-exporter'
    scheme: http
    metrics_path: '/metrics'
    static_configs:
      - targets: ['zealous-liberation.railway.internal:9187']
        labels:
          service: 'postgres'
          instance: 'n8n-db'
          environment: 'production'
  - job_name: 'redis-exporter'
    scheme: http
    metrics_path: '/metrics'
    static_configs:
      - targets: ['redis-exporter.railway.internal:9121']
        labels:
          service: 'redis'
          instance: 'n8n-cache'
          environment: 'production'
